language: node_js
node_js:
  - 6

cache:
  directories:
  - node_modules

script:
  - npm run build

before_deploy:
  - cp ./build/index.html ./build/200.html
  - cp ./build/index.html ./build/404.html

deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  fqdn: love-letter.ludovic-muller.fr
