language: node_js
node_js:
  - 6

before_script:
  - npm install

script:
  - npm run build

# See http://surge.sh/help/adding-a-200-page-for-client-side-routing
before_deploy:
  - mv ./build/index.html ./build/200.html

deploy:
  provider: surge
  project: ./build/
  domain: love-letter.ludovic-muller.fr
  on: master
  skip_cleanup: true
